name: backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backend
          # 기존 .coverage 파일이 있다면 확실하게 지워줍니다 (캐시 방지)
          rm -f .coverage  
          
          # manage.py test 대신 coverage로 테스트를 실행하여 리눅스용 .coverage 생성
          coverage run --source='.' manage.py test
          
          # 생성된 데이터를 바탕으로 html 리포트 생성
          coverage html

      - uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: backend/htmlcov/**
          retention-days: 5